site_name: ParallelPlots Documentation
site_url: https://marius-ui.github.io/ParallelPlots
theme:
  name: material  # You can change this theme
nav:
  - Home : index.md
  - Getting Started : getting_started.md
  - Usage : usage.md ,
  - Examples  : examples.md ,
  - Development  : development.md 
site_dir: site
