site_name: ParallelPlots Documentation
site_url: https://marius-ui.github.io/ParallelPlots
theme:
  name: material  # You can change this theme
nav:
  - Home: index.md
  - About: about.md
  - Installation: installation.md
  - Usage: usage.md
site_dir: site
