name: Documenter

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Check out the repository

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'  # Use the Julia version your package requires

      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build documentation
        run: julia --project=docs docs/make.jl

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Only deploy on the main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build